name: Download latest version from Data Dragon
on:
  schedule:
    - cron: 0/5 * * * *
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      id: use-node
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm install
    - name: Download latest version
      id: download-latest
      run: npm run download
    - run: echo ${{ steps.download-latest.outputs.shouldUpdate }
