name: Take screenshots
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - name: Take screenshots
        id: screenshots
        run: npm run screenshots
      - name: Commit screenshots
        if: ${{ steps.screenshots.outputs.should-commit == 'true' }}
        env:
          LATEST_VERSION: ${{ steps.screenshots.outputs.latest-version }}
        run: |
          git config user.name kristiandrex
          git config user.email cristiandrestorres@gmail.com
          git add -A
          git commit -m "Take screenshots to LoL version $LATEST_VERSION"
          git push
