name: Update to latest version from Data Dragon
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
      - run: npm install
      - name: Update to latest version
        id: update
        run: npm run update
      - name: Commit latest version
        if: ${{ steps.update.outputs.should-update == 'true' }}
        env:
          LATEST_VERSION: ${{ steps.update.outputs.latest-version }}
        run: |
          git config user.name kristiandrex
          git config user.email cristiandrestorres@gmail.com
          git add -A
          git commit -m "Update to LoL version $LATEST_VERSION"
          git push
