name: Update to latest version from Data Dragon
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  update:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - run: npm install
      - name: Download latest version
        id: download
        run: npm run update
      - name: Take screenshots
        if: steps.download.outputs.should-update == 'true'
        run: npm run screenshots
      - name: Commit latest version
        if: steps.download.outputs.should-update == 'true'
        env:
          LATEST_VERSION: ${{ steps.download.outputs.latest-version }}
        run: |
          git config user.name kristiandrex
          git config user.email cristiandrestorres@gmail.com
          git add -A
          git commit -m "Update to LoL version $LATEST_VERSION"
          git push
