name: Update to latest version from Data Dragon
on:
  schedule:
    - cron: 0 0 * * *
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        id: use-node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm install
      - name: Download latest version
        id: download-latest
        run: npm run download
      - name: Commit latest version
        if: ${{ steps.download-latest.outputs.shouldUpdate }}
        env:
          LATEST_VERSION: ${{ steps.download-latest.outputs.latestVersion }}
        run: |
          git config user.name kristiandrex
          git config user.email cristiandrestorres@gmail.com
          git add -A
          git commit -m "Update to LoL version $LATEST_VERSION"
          git push
