name: Update to latest patch from Data Dragon
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - run: npm install
      - name: Download latest patch
        id: download
        run: npm run update
      - name: Commit latest patch
        if: ${{ steps.download.outputs.should-commit == 'true' }}
        env:
          PATCH: ${{ steps.download.outputs.patch }}
        run: |
          git config user.name kristiandrex
          git config user.email cristiandrestorres@gmail.com
          git add -A
          git commit -m "Update to patch $PATCH"
          git push
